# Copy this file to paths.local.yaml and adjust paths for your machine.
root: .
autowebworld_root: ../path/to/...
webarena_root: ../path/to/...
artifacts_root: ./artifacts
fast_downward: ../path/to/...
